### ISSUE TITLE
自行编译的大杀器提示初始化Cipher出错

### ISSUE THREAD

**Issue by nebulakl** [chinashiyu/gfw.press#31]
Java版本: 
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

debug output:
[2016-07-31 18:22:32] 初始化Cipher出错：
java.security.InvalidKeyException: Illegal key size
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
    at javax.crypto.Cipher.implInit(Cipher.java:805)
    at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
    at javax.crypto.Cipher.init(Cipher.java:1396)
    at javax.crypto.Cipher.init(Cipher.java:1327)
    at press.gfw.Encrypt.encryptNet(Encrypt.java:595)
    at press.gfw.EncryptForwardThread.run(EncryptForwardThread.java:119)

求大神指点

**Comment by chinashiyu** [comment]
JAVA自带的加密包强度不够，要单独下载加密包：

http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by nebulakl** [comment]
解决啦，谢谢！
