### ISSUE TITLE
java8 貌似有兼容性问题

### ISSUE THREAD

**Issue by kcloze** [chinashiyu/gfw.press#58]
以下截取log文件一段报错日志：
```
[2017-08-22 12:59:56] 初始化Cipher出错：
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at press.gfw.Encrypt.encryptNet(Encrypt.java:595)
	at press.gfw.EncryptForwardThread.run(EncryptForwardThread.java:119)
[2017-08-22 12:59:59] 初始化Cipher出错：
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at press.gfw.Encrypt.encryptNet(Encrypt.java:595)
	at press.gfw.EncryptForwardThread.run(EncryptForwardThread.java:119)
[2017-08-22 13:00:02] 初始化Cipher出错：
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at press.gfw.Encrypt.encryptNet(Encrypt.java:595)
	at press.gfw.EncryptForwardThread.run(EncryptForwardThread.java:119)
[2017-08-22 13:00:02] 初始化Cipher出错：
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at press.gfw.Encrypt.encryptNet(Encrypt.java:595)
	at press.gfw.EncryptForwardThread.run(EncryptForwardThread.java:119)
[2017-08-22 13:00:05] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:06] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:08] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:08] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:11] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:12] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:13] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:13] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:14] 连接服务器出错：203.104.194.5:10041
[2017-08-22 13:00:15] 连接服务器出错：203.104.194.5:10041
```

**Comment by ugv7** [comment]
#31
