### ISSUE TITLE
ubuntu 下提示 nohup：重定向标准错误到标准输出

### ISSUE THREAD

**Issue by jeremy16601** [chinashiyu/gfw.press#69]
大神，ubuntu 下提示 nohup：重定向标准错误到标准输出

**Comment by xsfzwmh** [comment]
大神估计最近也疯了；或者是专注泡胡贵妃去了，果如斯，不仗义，忒！

**Comment by CaKrome** [comment]
@jeremy16601
把log文件发上来看看

**Comment by moonwater** [comment]
@CKrome 
我也碰到这个问题了 (nohup: redirecting stderr to stdout)：

Exception in thread "main" java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
	at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
	at java.awt.Window.getToolkit(Window.java:1358)
	at java.awt.Window.init(Window.java:506)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at press.gfw.Windows.<init>(Windows.java:259)
	at press.gfw.Windows.main(Windows.java:229)

**Comment by balbeleet** [comment]
把/etc/java-8-openjdk/accessibility.properties  下的（这里的java-8-openjdk对应你的目录）
assistive_technologies=org.GNOME.Accessibility.AtkWrapper 注释掉(行首加#)
